[functions.chat]
verify_jwt = false

[functions.memories]
verify_jwt = false

[functions.scheduler]
verify_jwt = false

[functions.game]
verify_jwt = false

[functions.web]
verify_jwt = false

[functions.tts]
verify_jwt = false

[functions.models]
verify_jwt = false

[functions.chat-test]
verify_jwt = false
