const MODEL_NAME = "YOUR_KEY_HERE";
// const MODEL_NAME = "YOUR_KEY_HERE";
// const MODEL_NAME = "YOUR_KEY_HERE";
// const MODEL_NAME = "YOUR_KEY_HERE";
const CHAT_API_ENDPOINT = "YOUR_SUPABASE_EDGE_FUNCTION_CHAT_URL";
const SUPABASE_URL = "YOUR_KEY_HERE";
const SUPABASE_ANON_KEY = "YOUR_KEY_HERE";
