window.SAVE_PRINCESS_CONFIG = {
  MODEL_NAME: "YOUR_MODEL_NAME",
  CHAT_API_ENDPOINT: "YOUR_SUPABASE_EDGE_FUNCTION_CHAT_URL",
  SUPABASE_URL: "YOUR_SUPABASE_URL",
  SUPABASE_ANON_KEY: "YOUR_SUPABASE_ANON_KEY"
};
