create table if not exists public.messages (
  id bigint generated by default as identity primary key,
  role text not null check (role in ('user', 'assistant')),
  content text not null,
  created_at timestamp default now()
);

alter table public.messages enable row level security;

drop policy if exists "Allow anonymous inserts into messages"
on public.messages;

drop policy if exists "Allow anonymous reads from messages"
on public.messages;

-- Keep RLS enabled. Add scoped policies later after authentication or an API proxy
-- defines who may read and write conversation rows.
