create table if not exists public.messages (
  id bigint generated by default as identity primary key,
  role text not null check (role in ('user', 'assistant')),
  content text not null,
  created_at timestamp default now(),
  conversation_id text not null default 'default'
);

-- Add conversation_id to existing table if missing
alter table public.messages add column if not exists conversation_id text not null default 'default';

alter table public.messages enable row level security;

-- MVP 开发期策略，正式版需要按用户隔离。

drop policy if exists "Allow anonymous inserts into messages" on public.messages;
drop policy if exists "Allow anonymous reads from messages" on public.messages;

create policy "Allow anonymous inserts into messages"
  on public.messages for insert
  to anon
  with check (role in ('user', 'assistant'));

drop policy if exists "Allow anonymous deletes from messages" on public.messages;

create policy "Allow anonymous deletes from messages"
  on public.messages for delete
  to anon
  using (true);
